# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Game

# Model Form Field configuration
form: $/goosy/leaderboard/models/game/fields.yaml

# Model Class name
modelClass: Goosy\Leaderboard\Models\Game

# Default redirect location
defaultRedirect: goosy/leaderboard/games

# Create page
create:
    title: backend::lang.form.create_title
    redirect: goosy/leaderboard/games/update/:id
    redirectClose: goosy/leaderboard/games

# Update page
update:
    title: backend::lang.form.update_title
    redirect: goosy/leaderboard/games
    redirectClose: goosy/leaderboard/games

# Preview page
preview:
    title: backend::lang.form.preview_title
